### Section 3 - Fundamentals of Python

### Lists
- Lists are like horizontal bookshelves
- Similar to arrays (C, C++) or vectors (R) in other programming languages
- Enumeration of lists in Python starts with zero (unlike with R that starts at 1)
- Lists allow for multiple object types 

### Lists and the range function - Python 3 vs 2
- Lists can be created by using the range function
- In Python 2.x, the range function generated a list 
- In Python 3.X, the range function creates an 'iterator' or a 'generator'
- Given you often create lists to iterate over, the updated function will create an iterable list with much less memory, only generating the necessary value at the moment of iteration (vs storing the entire list)
- range(10) == xrange(10) from Python 2.X

### Slicing a list
- Indexation allows for easy access of objects in sequence
- Slicing is essentially taking a subset out of your list (called 'subsetting' in R)
- You can pass positive or negative indexing or mix of two

<img src="Section 3 - image.png" style="width: 550px;"align="left"/>

In [9]:
lst = list('ABCDEFGHIJ')
print(lst[-8:7])
print(lst[-2:7])
print(lst[-8:1])
print(lst[-8:3])
print(lst[-5:7])

['C', 'D', 'E', 'F', 'G']
[]
[]
['C']
['F', 'G']


In [23]:
print(lst[2:7:1])
print(lst[6:1:-1])

['C', 'D', 'E', 'F', 'G']
['G', 'F', 'E', 'D', 'C']


### Tuples - immutable lists
- can still access similar to lists but cannot change objects within tuple

### Packages
- A module is simply a file containing Python definitions, functions and statements
- Putting code into modules is useful because of the ability to import the module functionality into your script
- A package is just a way of collecting related modules together within a single tree-like hierarchy
- Very complex packages (like NumPy or SciPy) have hundreds of individual modules so putting them into a directory-like structure keeps things organized and avoids name collisions

- Steps to using packages
    - 1: Find the package - Search internet resources based on your needs (look to github)
    - 2: Install the package - Open up terminal and enter in either "conda install 'package name'" or "pip install 'package name'"
    - 3: Import the package or function - "import 'package'" or "from 'package' import 'function'"
    

### Arrays in Python
- Can use a core module (array.arrays) or the NumPy package
- Use NumPy given it offers a much more versatile array object type
- Arrays in comparison with lists do not allow for more than one data type
- Benefits of arrays over lists are:
    - Arrays have many more methods available than lists with versatile and powerful functions for arrays with NumPy
    - Arrays allow for multi-dimensional objects

In [72]:
import numpy as np
a = np.array([[12.1,3,True,0],[8,9,90,10]])
a[0][2]

1.0

### Slicing an array
- Unlike lists, where the slice results in a copy of the list, when you slice an array, it is simply making a new view of the array
- Any changes made to a view of the array will affect the original array as well
- Reason for use of view (vs copy) is to protect the memory of the array
- If a true copy is desired, you can call the copy method np.array.copy

In [71]:
print(a)
b = a[1][:3]
print(b)
b[:] = 199
print(b)
print(a)

[[ 12.1   3.    1.    0. ]
 [  8.    9.   90.   10. ]]
[  8.   9.  90.]
[ 199.  199.  199.]
[[  12.1    3.     1.     0. ]
 [ 199.   199.   199.    10. ]]


In [73]:
print(a)
b = a.copy()[1][:3]
print(b)
b[:] = 199
print(b)
print(a)

[[ 12.1   3.    1.    0. ]
 [  8.    9.   90.   10. ]]
[  8.   9.  90.]
[ 199.  199.  199.]
[[ 12.1   3.    1.    0. ]
 [  8.    9.   90.   10. ]]
