In [2]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.ndim # number of dimensions

2

In [6]:
a.shape # the shape of the array

(3, 5)

In [7]:
a.size # the total number of elements in the array

15

In [8]:
a.dtype # the type of the element in the array. Memorize: dtype == data type. 

dtype('int32')

In [9]:
a.itemsize # the size in BYTES of each element. Depends on the data type.

4

## Creating Array

In [203]:
# Method 1. Creating prefixed arrarys

np.arange(10) # Count from 1 to N
np.arange(0,10,2) # Count from 1 to N with a step of S
np.linspace(0,10,111) # fill the gap between A and B evenly with N numbers
np.zeros((3,3)) # fill the array with 0s.
np.ones((3.3)) # fill the array with 1s.
np.empty((1,3)) # fill the array with nonsense. Note: the result might vary.

array([0, 2, 4, 6, 8])

In [44]:
# Method 2. From a Python list or tuple.
from_list=np.array([1,2,3])
# from_list=np.array(1,2,3) # Don't do this
from_tuple=np.array((4.1,5.2,6.3))
# from_tuple=np.array(4,5,6) # Don't do this
print(from_list)
print(from_tuple)

[1 2 3]
[ 4.1  5.2  6.3]


In [12]:
# Multi-dimensional array
from_list=np.array([[0,0],[1,1]]) # two points on a 2-dimensinal plane
# from_list=np.array([0,0],[1,1]) # Intential error. Think what's wrong?
print(from_list)

[[0 0]
 [1 1]]


In [25]:
# Specified data types
# e.g. np.int16, np.float32, complex,
array_int=np.array([1,2,3,4,5],dtype=np.int16)
print(array_int.dtype)
print(array_int)

# What happens if you int a number with decimals?
test=np.array([1.1,1.4,1.5,1.9],dtype=np.int16)
print(test)

int16
[1 2 3 4 5]
[1 1 1 1]


## Print Arrays

In [1]:
# Simply print it
a=np.arange(16).reshape(4,4) # 2d array
print(a)

b=np.arange(16) # 1d array
print(b)

c=np.arange(16).reshape(2,2,4) # 3d array
print(c)

# Will only corners are printed for large scale arrays
a=np.arange(1000000).reshape(1000,1000)
print(a)
# Can disable this feature by
# np.set_printoptions(threshold=np.inf)

NameError: name 'np' is not defined

## Basic Operations

Arithmetic operators on arrays apply **elementwise**. A **new array** is created and filled with the result.

In [60]:
a=np.array([1,10,100,1000])
a-10 # taking a number
b=np.arange(4)
a-b # taking an array
a**2 # taking to the power of N
np.cos(a) * 10 # triangular operation
a < 999 # Bool operation.

array([ True,  True,  True, False], dtype=bool)

#### The product operator: *

In [67]:
A=np.array([[1,2],
           [0,1]])
B=np.array([[3,0],
          [1,1]])
A*B # elementwise product
np.dot(A,B) # matrix product
A.dot(B) # another way of doing this
B.dot(A) # this is NOT correct. Refer to the law of matrix product.

array([[3, 6],
       [1, 3]])

#### Inplace operations

In [76]:
# Modify an exiting array rather than creating a new one
a=np.arange(6).reshape(2,3)
b=np.random.random((2,3))
a*=3 # inplace operation
a # it has been changed
b+=a # can add an integer array to a float array
b
# a+=b # but cannot add an float array to an integer array. Don't know what to do with the fractions!
# a # Will yield an error


array([[  0.03275135,   3.27802208,   6.20598768],
       [  9.88523176,  12.6041835 ,  15.61004853]])

When an operation concerns of multiple array types, the resulting array follows 
the more general or precise one.
E.g. 
integer + float = float (float is more precise than integer)
integer + float + complex = complex (complex is more precise than integer and float)

In [83]:
# upcasing type demonstration
a=np.ones(3, dtype=np.int)
a # integer array
b=np.linspace(np.pi,5,3)
b.dtype # float array
c=a+b
c.dtype # float array
d=np.exp(c*1j)
d.dtype # complex array


dtype('complex128')

#### basic statistics

In [109]:

a=np.random.random((3,3))
a
a.sum() # get the sum
a.min() # find the minimum
a.max() # find the maximum

# by default, the functions treat the array as a list of numbers 
# regardless of its dimension. To do it dimension wise:

b=np.arange(9).reshape(3,3)
print(b)
b.sum(axis=0) # sum by columns
b.sum(axis=1) # sum by rows
b.cumsum(axis=1) # cumulative sum each row(axis=1)/col(axis=0)
np.average(b) # average
np.std(a) # standard deviation
# all these operations can be done dimension-wise
# e.g.
np.average(b,axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 6.,  7.,  8.,  9.])

#### Universal Funcions

Common mathematical funcions such as sin, cos, exp.

In [118]:
A=np.arange(5)
print(A)
np.sin(A) # sin(x) function
np.cos(A) # cos(x) function
np.exp(A) # e^(x) exponential function
np.sqrt(A) # (x)^0.5 square root

B=np.array([3,56,1,4,-10])
np.add(A,B) # equals to A+B

[0 1 2 3 4]


array([ 3, 57,  3,  7, -6])

#### Indexing, slicing, and iterating

In [138]:
a=np.arange(10)**2
print(a)
a[7] # indexing
# a[10] # error because the index is 0...n-1
a[3:8] # slicing
a[:8] # -> begin to 8 (exclusive)
a[8:] # -> 8 to end
a[:] # -> begin to end (all)
a[3:8:2] # slicing with interval

# Challenge: reverse an array with slicing ?
a[::-1] # reversed

# iterating
for i in a:
    print(np.sqrt(i))
# iterating with a function
def f(x): return x-10
for i in a:
    print(f(i))


[ 0  1  4  9 16 25 36 49 64 81]
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
-10
-9
-6
-1
6
15
26
39
54
71


In multi-dimensional arrays, dimensions are separated by commas.

In [3]:
b=np.arange(20).reshape(4,5)
print(b)
b[0,2] # same as b[0][2], pick an element
b[:3,1:3] # slicing. (row, col)
b[:,-1] # for every row, pick the last column

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 4,  9, 14, 19])

##### Slicing: Advanced topics

when specification for any indices are missing, they're assumed to be complete slices.

In [6]:
b[0] # equivalent to b[0,:]

2

use dots(...) to represent as many dimensions as needed of the remaining dimensions

In [ ]:
c=np.arange(27).reshape(3,3,3)
print(c)
c[1,...] # same as c[1] or c[1,:,:]
c[...,1] # same as c[:,:,1]

Iterating through multi-dimensional array

In [159]:
for row in b: # naive iteration (per row)
    print(row)

for row in b: # per element
    for element in row:
        print(element)
        
for element in b.flat: # per element, a more elegant way
    print(element)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


exercise, iterate with `for` command through a three dimensional array C, where `C=np.arange(27).reshape(3,3,3)`

## Shape Manipulation

### 1. Transformation

In [186]:
a=np.arange(28).reshape(4,7)
a.shape
a.T # Matrix transpose
a.ravel() # flatten the array
a.reshape(2,2,7) # better practice
a.reshape(4,-1) # -1 means other dimensions will be calculated automatically

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [201]:
# Advanced: raising the dimension
a=np.arange(6).reshape(2,3)
print(a) # a has 2 diemnsions
print(a[:,np.newaxis]) # raising a to 3D
print(a[:,np.newaxis,np.newaxis]) # raising a to 4D

[[0 1 2]
 [3 4 5]]
[[[0 1 2]]

 [[3 4 5]]]
[[[[0 1 2]]]


 [[[3 4 5]]]]


### 2. Aggregation

In [11]:
a=np.array([[8,-1],[4,9]])
b=np.array([[0.2,0.9],[-0.02,0.04]])
v=np.vstack((a,b)) # stack them vertically
print(v)
h=np.hstack((a,b)) # stack them horizontally
print(h)

[[ 8.   -1.  ]
 [ 4.    9.  ]
 [ 0.2   0.9 ]
 [-0.02  0.04]]
[[ 8.   -1.    0.2   0.9 ]
 [ 4.    9.   -0.02  0.04]]


### 3. Split

In [10]:
np.hsplit(h,2) # split into 2 arrays
np.vsplit(v,2) # slit after the columns

[array([[ 8., -1.],
        [ 4.,  9.]]), array([[ 0.2 ,  0.9 ],
        [-0.02,  0.04]])]